### ISSUE TITLE
pyblish hangs when family is None

### ISSUE THREAD

**Issue by hannesdelbeke** [pyblish/pyblish#8]
Had a class that used a variable for the family. 
When during refactoring the var became null, Pyblish just hang, stuck in the collecting phase on this plugin.
Had to shift click X to force close the QML Pyblish GUI.

example reproduction:
```
class TestPlugin(pyblish.api.ContextPlugin):
    label = "Collect: TestPlugin"
    order = pyblish.api.CollectorOrder
    hosts = ["maya"]

    def process(self, context):
        instance = context.create_instance('this instance will hang', family=None)
```

obvious solution is prevent family from being None but would be good if Pyblish checks for this too

**Comment by hannesdelbeke** [comment]
only hangs in QML, not when using commands
```
import pyblish.util

ct = pyblish.util.collect()
print(ct)
print ("test")
```
outputs:
```
[pyblish.plugin.Instance("this instance will hang"), pyblish.plugin.Instance("C:/redacted.ma")]
test
```

**Comment by mottosso** [comment]
Thanks for this, yes that makes sense. Would you submit a PR with an assertion for the family name? It simply should not be allowed to be `None`.

**Comment by hannesdelbeke** [comment]
TBH I'm not sure atm where to add the assert, apologies.
Been looking through the source code and reading the docs all day but don't yet fully understand the architecture.
while trying to figure out where to add the assert, I was getting the hanging consistently in QML for about 30 minutes
and now it suddenly started throwing an assert. Yet I haven't implemented one!

```
Already installed, uninstalling..
Pyblish QML shutdown successful.
Setting up Pyblish QML in Maya
Setting up Pyblish QML in Maya
uninstalling..
Installing..
aboutToQuit..
Maya host..
event filter..
# pyblish_qml.host : Installed event filter # 
Using Python @ 'C:/Users/hanne/AppData/Local/Programs/Python/Python38/python.exe'
Using PyQt5 @ 'None'
Targets: default
# pyblish_qml.host : Success. QML server available as pyblish_qml.api.current_server() # 
Starting pyblish-qml
Done, don't forget to call `show()`
WindowSize = [430, 600]
ContextLabel = Maya
HeartbeatInterval = 60
HiddenSections = ['Collect']
WindowTitle = Pyblish (Maya)
WindowPosition = [100, 100]
Settings:
Entering state: "alive"
Entering state: "clean"
Entering state: "ready"
Entering state: "hidden"
Entering state: "visible"
Entering state: "initialising"
Entering state: "collecting"
File "C:\Projects\REDACT\3rd_party_packages\pyblish_qml\control.py", line 1056, in update_context
Traceback (most recent call last):
File "C:\Projects\REDACT\3rd_party_packages\pyblish_qml\models.py", line 430, in add_section
self.add_section(item["category"])
File "C:\Projects\REDACT\3rd_party_packages\pyblish_qml\models.py", line 408, in add_instance
item_model.add_instance(instance.to_json())
AssertionError
assert isinstance(name, str)
```

disabling the testplugin now removes the assert error. this is exactly what we want but why did it suddenly change behaviour? AFAIK no code was changed

**Comment by hannesdelbeke** [comment]
I'll close this for now since it now behaves the way it should, and repro is not consistent anymore
